### ISSUE TITLE
personal sign signature created in the web browser slush wallet could not be verified

### ISSUE THREAD

**Issue by gksdnf050** [MystenLabs/ts-sdks#273]
## Steps to Reproduce Issue

	1.	Access the dapp that uses slush wallet in your browser (chrome, safari)
	2.	Sign with your browser slush wallet
	3.	verify

## Expected Result

It should verify successfully.

## Actual Result
verify works fine when I access the slush wallet in-app browser and sign with it. 
verify fails when I sign with an external browser (Chrome, Safari).

## Environment Information

- sdk version: @mysten/sui 1.29.0

**Comment by williamrobertson13** [comment]
Thanks for the report! We'll have this fixed in https://github.com/MystenLabs/ts-sdks/pull/274.

**Comment by gksdnf050** [comment]
I still can't verify the signature signed in brwoser slush wallet, can you give me the sample code?

**Comment by williamrobertson13** [comment]
It'll be included in `@mysten/dapp-kit@0.16.2` / `@mysten/slush-wallet@0.1.2` which will get released today!
